version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - mosaic:/var/lib/postgresql/data
    env_file:
      - ./.env


  # nginx:
    # image: nginx:1.21.3-alpine
    # ports:
      # - "80:80"

    # volumes:
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      # - static_value:/var/html/django_static/
      # - media_value:/var/html/media/

    # depends_on:
      # - db


  web:
    build: ../mosaic_backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  
  
  # the old approach
  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ../frontend/:/app/result_build/


  frontend:
    env_file: .env
    build: ../frontend/ 
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  gateway:
    build: 
      context: ../gateway/
      dockerfile: Dockerfile
    volumes:
      # new
      - static:/staticfiles/ 
      - static_value:/var/html/django_static/
      - media_value:/var/html/media/
    ports:
      - 8000:80 


volumes:
  mosaic:
  static_value:
  media_value:
  static:
