version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - mosaic:/var/lib/postgresql/data
    env_file:
      - ./.env

  web:
    build: ../mosaic_backend
    restart: always
    volumes:
      - static:/backend_static
      - media_value:/app/media
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    env_file: .env
    # environment:
    #   - REACT_APP_API_URL="https://tessera.hopto.org/"
    
    build: ../frontend/ 
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  gateway:
    build: 
      context: ../gateway/
      dockerfile: Dockerfile
    depends_on:
      - web
    volumes:
      - static:/staticfiles
      - media_value:/app/media
    ports:
      - 8000:80 

volumes:
  static:
  media_value:
  mosaic:
