name: Mosaic-app workflow
on: 
  push:
    branches: 
      - main
      - dev
      - 'backend/**'
      - 'frontend/**'
      - test-workflow
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      db:
          image: postgres:13.0-alpine
          env:
            POSTGRES_USER: django_user
            POSTGRES_PASSWORD: django_password
            POSTGRES_DB: django_db
          ports:
            - 5432:5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r ./mosaic_backend/requirements.txt 

    - name: Test with django tests
      env:
        POSTGRES_USER: django_user
        POSTGRES_PASSWORD: django_password
        POSTGRES_DB: django_db
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
      run: |
        cd mosaic_backend/
        python manage.py test

